#ifndef SPRITES_AUTOGEN_H
#define SPRITES_AUTOGEN_H
/* Warning! This file is automatically generated by 
   utils/genspritelist.sh. Do not edit! */

void sprite_types_register();
extern sprite_type_t airballoon;
extern sprite_type_t biplane;
extern sprite_type_t bird;
extern sprite_type_t blueplane;
extern sprite_type_t bomb;
extern sprite_type_t bonusmachine;
extern sprite_type_t bonus;
extern sprite_type_t bouncer;
extern sprite_type_t bullet;
extern sprite_type_t cannon;
extern sprite_type_t cannonball;
extern sprite_type_t cloud;
extern sprite_type_t ldust;
extern sprite_type_t sdust;
extern sprite_type_t dsmoke;
extern sprite_type_t energymeter;
extern sprite_type_t explosion;
extern sprite_type_t fire;
extern sprite_type_t hangar;
extern sprite_type_t mark;
extern sprite_type_t msg_kill;
extern sprite_type_t msg_damage;
extern sprite_type_t msg_fire;
extern sprite_type_t missile;
extern sprite_type_t parachute;
extern sprite_type_t puff;
extern sprite_type_t blacksmoke;
extern sprite_type_t zeppelin;

#endif
